### ISSUE TITLE
Get SQS Queue URL from ARN

### ISSUE THREAD

**Issue by dinkzilla** [aws/aws-sdk#15]
It appears that an SQS ARN has all of the information needed to construct a queue URL. A function to do this mapping without having to make an API call would be useful.

Usecase Example:
- A Lambda is triggered off of an SQS.
- The Lambda takes in batches, so it wants to delete the messages individually as they are completed so that if one fails the others in the batch do not need to go back on the queue (as they would if you used the callback).
- The messages sent into the Lambda already contain the SQS ARN, though not the URL, which is needed to delete. If we could delete using the ARN or translate the ARN easily into the queue URL, we can avoid having to add a queue environment variable to the lambda.

I can create create a pull request if this idea is deemed valuable.

**Comment by HDsouza-FPSS** [comment]
@ajredniwja, @srchase any chance there's an update on this?

**Comment by NinovanderMark** [comment]
@ajredniwja @srchase It's been quite a while since the last update, do you know if and when we can expect this new field to be available?

**Comment by Leigh-M** [comment]
If you're provisioning via SAM template (or CloudFormation) you can just reference it in your template.yaml and pass in to lambda as an environment variable like this:

```
QueuedInvocationHandler:
  Type: AWS::Serverless::Function
  Properties:
    Handler: ....
    CodeUri: .......
    Environment:
      Variables:
        queueUrl: !Ref someQueueInTemplate
```

It is then available in process.env as:

`const { queueUrl } = process.env;`

**Comment by mike-driver** [comment]
Python:
def getSQSUrlFromEventSourceArn(eventSourceARN):
    # from this:
    # arn:aws:sqs:eu-west-2:422998111546:sqs003
    # to this:
    # https://sqs.eu-west-2.amazonaws.com/422998111546/TestInputQueue
    
    StrSplit = eventSourceARN.split(":")
    
    service = StrSplit[2]
    region = StrSplit[3]
    accountId = StrSplit[4]
    queueName = StrSplit[5]
    
    queueUrl = "https://" + service + "." + region + ".amazonaws.com/" + accountId + '/' + queueName
    return{
        queueUrl    
    }

**Comment by delsinz** [comment]
What's the reason behind the design decision of using queue url instead of queue ARN for a lot of the SQS commands anyway?

**Comment by leifbennett** [comment]
Running into the converse while trying to subscribe an SQS queue to an SNS topic. I'm using the 2.x SDK (Java). I've got the queue URL from creating it with a CreateQueueRequest. However, the SNS SubscribeRequest builder needs the queue ARN for its endpoint.

Is there example code of using SNS over SQS, preferably in Java and using the 2.x SDK (or some equally good library)? That might show a workaround for this problem.

**Comment by mike-driver** [comment]
GetQueueAttributes.QueueArn

**Comment by Leigh-M** [comment]
@leifbennett for any standard serverless patterns check: https://serverlessland.com/patterns  (the patterns & videos are awesome)

That sounds like a basic SNS -> SQS fan-out pattern you are describing there will probably be an official example as IaC (Infrastructure as Code) that you can simply deploy from the above website, or here is one I wrote recently in AWS SAM (as you can see it expects your index.js file to be in /dist folder with an exports.handler function - written for nodeJs - there will be Java examples in the patterns repo)

```
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Example SAM SNS -> SQS fan-out pattern 

Resources:
  # SQS queues
  MyEventsQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub ${AWS::StackName}-MyEventsQueue
      MessageRetentionPeriod: 1209600 # 14 DAYS
      ReceiveMessageWaitTimeSeconds: 10 # mid-level polling. 0-20 secs short-long polling
      Tags:
        - Key: PROJECT
          Value: 'YOUR-PROJECT-NAME'
        - Key: PROVISIONEDBY
          Value: 'SAM/ CLOUDFORMATION'

  # SNS topics
  MyEventsSNSTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName : MyEventsSNSTopic

  # lambdas
  MyEventsHandler:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: dist/MyEventsHandler
      Handler: index.handler
      FunctionName: !Sub ${AWS::StackName}-MyEventsHandler
      Runtime: nodejs14.x
      MemorySize: 128
      Timeout: 10
      ReservedConcurrentExecutions: 2 # protect our 1000 concurrent executions account limit from runaway lambdas
      Policies:
        - SQSPollerPolicy:
            QueueName: !GetAtt MyEventsQueue.QueueName
      Events:
        SQSTrigger:
          Type: SQS
          Properties:
            Queue: !GetAtt MyEventsQueue.Arn
      Tags:
        PROJECT: 'YOUR-PROJECT-NAME'
        PROVISIONEDBY: 'SAM/ CLOUDFORMATION'

  # allows SNS to publish to this SQS queue
  SnsToSqsPolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: "Allow SNS publish to SQS"
            Effect: Allow
            Principal: 
              Service: "sns.amazonaws.com"
            Resource: !GetAtt MyEventsQueue.Arn
            Action: SQS:SendMessage
            Condition:
              ArnEquals:
                aws:SourceArn: !Ref MyEventsSNSTopic
      Queues:
        - Ref: MyEventsQueue

Outputs:
  MySqsQueueArn:
    Description: SQS queue ARN
    Value: !GetAtt MyEventsQueue.Arn
  MyEventsSNSTopicArn:
    Description: SNS topic ARN
    Value: !Ref MyEventsSNSTopic
```
