### ISSUE TITLE
Update tags on Glue jobs

### ISSUE THREAD

**Issue by kdaily** [aws/aws-sdk#91]
Original issue: https://github.com/boto/boto3/issues/2896 by @ismailsimsek.

> Glue.Client.update_job is not supporting to add Tags, is there any reason its not supported?
> 
> https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/glue.html#Glue.Client.update_job
> 
> ```
> File "/home/xxxx/.local/lib/python3.7/site-packages/botocore/client.py", line 357, in _api_call
>  return self._make_api_call(operation_name, kwargs)
> File "/home/xxxx/.local/lib/python3.7/site-packages/botocore/client.py", line 649, in _make_api_call
>  api_params, operation_model, context=request_context)
> File "/home/xxxx/.local/lib/python3.7/site-packages/botocore/client.py", line 697, in _convert_to_request_dict
>  api_params, operation_model)
> File "/home/xxxx/.local/lib/python3.7/site-packages/botocore/validate.py", line 293, in serialize_to_request
>  raise ParamValidationError(report=report.generate_report())
> botocore.exceptions.ParamValidationError: Parameter validation failed:
> Unknown parameter in JobUpdate: "Tags", must be one of: Description, LogUri, Role, ExecutionProperty, Command, DefaultArguments, NonOverridableArguments, Connections, MaxRetries, AllocatedCapacity, Timeout, MaxCapacity, WorkerType, NumberOfWorkers, SecurityConfiguration, NotificationProperty, GlueVersion
> ```
> 
> **Describe the solution you'd like**
> could you please add support to update existing glue jobs with "Tags" ?

**Comment by kdaily** [comment]
V380076524

**Comment by w0rks74710n** [comment]
My colleague and I created a reusable Custom Resource (https://github.com/aws-samples/aws-glue-tagger-sar/) that addresses points raised in this issue and some more:

Automatic propagation of stack tags to AWS Glue resources.
Updating tags.
Having tagging syntax consistent with other AWS CloudFormation resources.

Usage example:

```
  GlueTaggerTestStack:
  Type: 'Custom::GlueTaggerTestStack'
  DependsOn:
    - 'MyJob1'
    - 'AWSGlueTagger'
  Properties:
    ServiceToken: !ImportValue GlueTaggerFunction
    ResourceArn:
      - !Sub 'arn:aws:glue:${AWS::Region}:${AWS::AccountId}:job/${MyJob1}'
    Tags:
      - Key: "cost_id"
        Value: "0000"
      - Key: "owner"
        Value: "myorg"
      - Key: "project"
        Value: "myproject"
```
@kdaily @stobrien89 @trevorrowe
